// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1sogD7runLrqyh-_ub3n3tt3LO7dfDQs',
    appId: '1:787452422809:web:859664deb400b7d3da6608',
    messagingSenderId: '787452422809',
    projectId: 'flutter-tutorial-e7b58',
    authDomain: 'flutter-tutorial-e7b58.firebaseapp.com',
    storageBucket: 'flutter-tutorial-e7b58.appspot.com',
    measurementId: 'G-W2HD3DN14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGAeI5kqpoazzkXYxAQtR2BJObGWlh6c',
    appId: '1:787452422809:android:07a5207a45f97ba3da6608',
    messagingSenderId: '787452422809',
    projectId: 'flutter-tutorial-e7b58',
    storageBucket: 'flutter-tutorial-e7b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQsBGgWuOKawW7IRW5zvpEriVWBOE_N8',
    appId: '1:787452422809:ios:b7150ee885db76f1da6608',
    messagingSenderId: '787452422809',
    projectId: 'flutter-tutorial-e7b58',
    storageBucket: 'flutter-tutorial-e7b58.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQsBGgWuOKawW7IRW5zvpEriVWBOE_N8',
    appId: '1:787452422809:ios:b7150ee885db76f1da6608',
    messagingSenderId: '787452422809',
    projectId: 'flutter-tutorial-e7b58',
    storageBucket: 'flutter-tutorial-e7b58.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1sogD7runLrqyh-_ub3n3tt3LO7dfDQs',
    appId: '1:787452422809:web:a04f2ff80ab9dff2da6608',
    messagingSenderId: '787452422809',
    projectId: 'flutter-tutorial-e7b58',
    authDomain: 'flutter-tutorial-e7b58.firebaseapp.com',
    storageBucket: 'flutter-tutorial-e7b58.appspot.com',
    measurementId: 'G-NHFR7JHN9F',
  );

}